services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=bcf
      - MYSQL_ROOT_HOST=%
      
  api:
    build: ./api
    ports: 
      - "3000:3000"
    networks:
      - frontend
      - backend
    depends_on:
      - "db"
    restart: always

  website:
    build: ./web/
    ports:
      - "80:80"
    networks:
      - frontend

networks:
  frontend: {}
  backend: {}